// Build script untuk inject environment variables ke env.js
// Digunakan saat deploy di Netlify
// Usage: node build.js

const fs = require('fs');
const path = require('path');

// Ambil environment variables dari Netlify (atau fallback ke default)
const SUPABASE_URL = process.env.SUPABASE_URL || 'https://dthgezcoklarfwbzkqym.supabase.co';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0aGdlemNva2xhcmZ3YnprcXltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0MDg0OTAsImV4cCI6MjA3ODk4NDQ5MH0.cyPwOIFsbfKc0akAhAcVVkhAIdAi_Iyt4DU2B-eVpwk';

// Generate env.js content
const envContent = `// Environment Configuration
// Auto-generated by build.js
// DO NOT EDIT MANUALLY - This file is generated during build

export const SUPABASE_URL = '${SUPABASE_URL}';
export const SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY}';
`;

// Write to env.js
const envPath = path.join(__dirname, 'env.js');
fs.writeFileSync(envPath, envContent, 'utf8');

console.log('✅ env.js generated successfully');
console.log(`   SUPABASE_URL: ${SUPABASE_URL.substring(0, 30)}...`);
console.log(`   SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY.substring(0, 30)}...`);

