// Build script untuk inject environment variables ke env.js
// Digunakan saat deploy di Netlify
// Usage: node build.js

const fs = require('fs');
const path = require('path');

// Ambil environment variables dari environment (Netlify, CI/CD, atau local .env)
// SECURITY: NO HARDCODED CREDENTIALS - Must be provided via environment variables
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY;

// Validate that environment variables are provided
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.error('❌ ERROR: Missing required environment variables!');
    console.error('   Please set SUPABASE_URL and SUPABASE_ANON_KEY environment variables.');
    console.error('   For local development, create a .env file or set them in your environment.');
    process.exit(1);
}

// Additional validation - ensure values are not placeholders
if (SUPABASE_URL === 'YOUR_SUPABASE_URL' || SUPABASE_ANON_KEY === 'YOUR_SUPABASE_ANON_KEY') {
    console.error('❌ ERROR: Environment variables contain placeholder values!');
    console.error('   Please provide actual Supabase credentials.');
    process.exit(1);
}

// Generate env.js content
const envContent = `// Environment Configuration
// Auto-generated by build.js
// DO NOT EDIT MANUALLY - This file is generated during build

export const SUPABASE_URL = '${SUPABASE_URL}';
export const SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY}';
`;

// Write to env.js
const envPath = path.join(__dirname, 'env.js');
fs.writeFileSync(envPath, envContent, 'utf8');

console.log('✅ env.js generated successfully');
console.log(`   SUPABASE_URL: ${SUPABASE_URL.substring(0, 30)}...`);
console.log(`   SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY.substring(0, 30)}...`);

