// Script untuk menyiapkan folder deploy manual ke Netlify
// Usage: node prepare-deploy.js

const fs = require('fs');
const path = require('path');

const DEPLOY_FOLDER = 'deploy';
const REQUIRED_FILES = [
    'index.html',
    'app.js',
    'auth.js',
    'database.js',
    'calculation.js',
    'validation.js',
    'logger.js',
    'env.js',
    'style.css',
    'sw.js',
    'manifest.json',
    'package.json'
];

// netlify.toml akan dibuat khusus untuk deploy manual (tanpa build command)

const OPTIONAL_FILES = [
    'README.md'
];

console.log('🚀 Menyiapkan folder deploy untuk Netlify...\n');

// 1. Validasi environment variables
console.log('1. Memvalidasi environment variables...');
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.error('❌ ERROR: Environment variables tidak ditemukan!');
    console.error('   Set environment variables terlebih dahulu:');
    console.error('   Windows (PowerShell):');
    console.error('     $env:SUPABASE_URL="https://dthgezcoklarfwbzkqym.supabase.co"');
    console.error('     $env:SUPABASE_ANON_KEY="your-key-here"');
    console.error('   Windows (CMD):');
    console.error('     set SUPABASE_URL=https://dthgezcoklarfwbzkqym.supabase.co');
    console.error('     set SUPABASE_ANON_KEY=your-key-here');
    console.error('   Linux/Mac:');
    console.error('     export SUPABASE_URL="https://dthgezcoklarfwbzkqym.supabase.co"');
    console.error('     export SUPABASE_ANON_KEY="your-key-here"');
    process.exit(1);
}

console.log('   ✅ Environment variables ditemukan\n');

// 2. Generate env.js
console.log('2. Generate env.js...');
const envContent = `// Environment Configuration
// Auto-generated by prepare-deploy.js
// DO NOT EDIT MANUALLY - This file is generated during build

export const SUPABASE_URL = '${SUPABASE_URL}';
export const SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY}';
`;

fs.writeFileSync(path.join(__dirname, 'env.js'), envContent, 'utf8');
console.log('   ✅ env.js generated\n');

// 3. Buat folder deploy
console.log('3. Membuat folder deploy...');
if (fs.existsSync(DEPLOY_FOLDER)) {
    console.log('   ⚠️  Folder deploy sudah ada, menghapus...');
    fs.rmSync(DEPLOY_FOLDER, { recursive: true, force: true });
}
fs.mkdirSync(DEPLOY_FOLDER, { recursive: true });
fs.mkdirSync(path.join(DEPLOY_FOLDER, 'js'), { recursive: true });
console.log('   ✅ Folder deploy dibuat\n');

// 4. Copy required files
console.log('4. Menyalin file-file yang diperlukan...');
let copiedCount = 0;
let missingCount = 0;
const missingFiles = [];

REQUIRED_FILES.forEach(file => {
    const sourcePath = path.join(__dirname, file);
    let destPath = path.join(DEPLOY_FOLDER, file);
    
    // Handle js/store.js
    if (file === 'js/store.js') {
        destPath = path.join(DEPLOY_FOLDER, 'js', 'store.js');
    }
    
    if (fs.existsSync(sourcePath)) {
        // Create directory if needed
        const destDir = path.dirname(destPath);
        if (!fs.existsSync(destDir)) {
            fs.mkdirSync(destDir, { recursive: true });
        }
        
        fs.copyFileSync(sourcePath, destPath);
        console.log(`   ✅ ${file}`);
        copiedCount++;
    } else {
        console.log(`   ❌ ${file} - FILE TIDAK DITEMUKAN!`);
        missingFiles.push(file);
        missingCount++;
    }
});

// Copy optional files
OPTIONAL_FILES.forEach(file => {
    const sourcePath = path.join(__dirname, file);
    const destPath = path.join(DEPLOY_FOLDER, file);
    
    if (fs.existsSync(sourcePath)) {
        fs.copyFileSync(sourcePath, destPath);
        console.log(`   ✅ ${file} (optional)`);
    }
});

// Buat netlify.toml khusus untuk deploy manual (tanpa build command)
console.log('5. Membuat netlify.toml untuk deploy manual...');
const netlifyTomlPath = path.join(__dirname, 'netlify.toml');
const deployNetlifyTomlPath = path.join(DEPLOY_FOLDER, 'netlify.toml');

if (fs.existsSync(netlifyTomlPath)) {
    let netlifyTomlContent = fs.readFileSync(netlifyTomlPath, 'utf8');
    
    // Hapus build command untuk deploy manual (file sudah di-build lokal)
    // Ganti [build] section dengan tanpa command sama sekali
    netlifyTomlContent = netlifyTomlContent.replace(
        /\[build\]\s*\n\s*# Build command.*\n\s*command\s*=\s*"[^"]*"\s*\n/g,
        '[build]\n  # No build command needed for manual deploy (files already built locally)\n'
    );
    
    // Hapus semua baris yang mengandung command = (termasuk yang sudah di-comment)
    netlifyTomlContent = netlifyTomlContent.replace(
        /^\s*#?\s*command\s*=.*$/gm,
        '  # command removed for manual deploy'
    );
    
    // Pastikan tidak ada command yang aktif
    netlifyTomlContent = netlifyTomlContent.replace(
        /command\s*=\s*"npm run build"/g,
        '# command removed for manual deploy'
    );
    
    fs.writeFileSync(deployNetlifyTomlPath, netlifyTomlContent, 'utf8');
    console.log(`   ✅ netlify.toml (modified for manual deploy - no build command)\n`);
} else {
    // Buat netlify.toml minimal untuk deploy manual
    const minimalNetlifyToml = `# Netlify Configuration for Manual Deploy
# Build command tidak diperlukan karena file sudah di-build lokal

[build]
  # No build command - files already prepared locally
  publish = "/"

# Redirect rules untuk SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://dthgezcoklarfwbzkqym.supabase.co; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https://cdn.jsdelivr.net https://dthgezcoklarfwbzkqym.supabase.co https://*.supabase.co; frame-ancestors 'none';"

# Headers khusus untuk service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"
    Content-Type = "application/javascript"

# Headers untuk manifest.json
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=3600"

# Headers untuk JavaScript modules (ESM)
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# Headers untuk CSS
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# Headers untuk HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
`;
    fs.writeFileSync(deployNetlifyTomlPath, minimalNetlifyToml, 'utf8');
    console.log(`   ✅ netlify.toml (created for manual deploy)\n`);
}

console.log(`   📊 Total: ${copiedCount} file berhasil, ${missingCount} file hilang\n`);

// 5. Validasi
if (missingCount > 0) {
    console.error('❌ ERROR: Beberapa file penting tidak ditemukan!');
    console.error('   File yang hilang:');
    missingFiles.forEach(file => {
        console.error(`   - ${file}`);
    });
    console.error('\n   Pastikan semua file ada sebelum deploy!');
    process.exit(1);
}

// 6. Summary
console.log('✅ Folder deploy siap!');
console.log(`\n📁 Lokasi: ${path.resolve(DEPLOY_FOLDER)}`);
console.log('\n📋 Langkah selanjutnya:');
console.log('   1. Buka Netlify Dashboard: https://app.netlify.com');
console.log('   2. Klik "Add new site" → "Deploy manually"');
console.log('   3. Drag & drop folder "deploy" ke drop zone');
console.log('   4. Tunggu deploy selesai');
console.log('\n💡 Atau gunakan Netlify CLI:');
console.log('   cd deploy');
console.log('   netlify deploy --prod');
console.log('');
